services:
  mysql:
    image: mysql
    ports:
      - "3310:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=db_adi
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"